# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arithmetic/subtract.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arithmetic/subtract.proto',
  package='Arithmetic',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x61rithmetic/subtract.proto\x12\nArithmetic\"\x19\n\x07Minuend\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1c\n\nDifference\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32I\n\x0bSubtraction\x12:\n\x0bSubtractOne\x12\x13.Arithmetic.Minuend\x1a\x16.Arithmetic.Differenceb\x06proto3'
)




_MINUEND = _descriptor.Descriptor(
  name='Minuend',
  full_name='Arithmetic.Minuend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Arithmetic.Minuend.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=66,
)


_DIFFERENCE = _descriptor.Descriptor(
  name='Difference',
  full_name='Arithmetic.Difference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Arithmetic.Difference.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Minuend'] = _MINUEND
DESCRIPTOR.message_types_by_name['Difference'] = _DIFFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Minuend = _reflection.GeneratedProtocolMessageType('Minuend', (_message.Message,), {
  'DESCRIPTOR' : _MINUEND,
  '__module__' : 'arithmetic.subtract_pb2'
  # @@protoc_insertion_point(class_scope:Arithmetic.Minuend)
  })
_sym_db.RegisterMessage(Minuend)

Difference = _reflection.GeneratedProtocolMessageType('Difference', (_message.Message,), {
  'DESCRIPTOR' : _DIFFERENCE,
  '__module__' : 'arithmetic.subtract_pb2'
  # @@protoc_insertion_point(class_scope:Arithmetic.Difference)
  })
_sym_db.RegisterMessage(Difference)



_SUBTRACTION = _descriptor.ServiceDescriptor(
  name='Subtraction',
  full_name='Arithmetic.Subtraction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=98,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubtractOne',
    full_name='Arithmetic.Subtraction.SubtractOne',
    index=0,
    containing_service=None,
    input_type=_MINUEND,
    output_type=_DIFFERENCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUBTRACTION)

DESCRIPTOR.services_by_name['Subtraction'] = _SUBTRACTION

# @@protoc_insertion_point(module_scope)
